Rudimentary non-production distributed Python API
nod-ai/SHARK-Runtime pull request #64
Opened 2023-08-01 17:25 UTC by sogartar

Functionality meant to validate that distributed execution with collectives is working correctly.
This should be thrown away if we have a proper implementation.

2023-08-07 16:44 UTC, nithinsubbiah commented
@sogartar I think there has been updates to TOM, could you rebase and push again?

2023-08-07 17:12 UTC, sogartar commented
@nithinsubbiah I change the PR target branch for the purpose of doing the code review without interruptions.

2023-08-07 19:36 UTC, nithinsubbiah requested changes
Everything looks good to me. I'd recommend adding an example script showcasing how to use this API. Also, would change the patch name to just `Distributed Inference using Python API`

2023-08-10 18:42 UTC, nithinsubbiah approved these changes

2023-08-10 18:44 UTC, merged